### 1. Основные понятия и структуры PyTorch<br>
- Создайте случайный FloatTensor размера 3x4x5
- Выведите его форму (shape)
- Приведите его к форме 6х10
- Создайте случайный IntTensor размера 10
- Умножьте созданный FloatTensor на созданный IntTensor поэлементно
- Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти
- Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
- Создайте единичный тензор размера 5x6
- Переведите его в формат numpy

In [1]:
!pip install torch torchvision

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import torch
import torchvision
import numpy as np

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
a_tensor = torch.randn(3, 4, 5)

In [4]:
# Выведите его форму (shape)
a_tensor.shape

torch.Size([3, 4, 5])

In [5]:
# Приведите его к форме 6 X 10
b_tensor = torch.reshape(a_tensor, (6, 10))
b_tensor.shape

torch.Size([6, 10])

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
v = torch.randint(10, size=(10,))
v

tensor([9, 1, 8, 9, 5, 5, 8, 4, 2, 2])

In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.mul(b_tensor, v)

tensor([[ 1.6460e+00,  5.3626e-01,  2.4133e+00,  3.3175e+00, -2.7593e+00,
         -8.5260e+00, -1.7259e+01, -2.4736e-01, -3.9111e-01,  1.9442e+00],
        [ 7.4934e+00, -9.8436e-01, -2.6171e+01,  6.6348e+00, -1.7599e+00,
          3.0892e+00,  8.7916e+00,  1.1585e+00, -2.5157e-02,  7.7874e-01],
        [ 1.7653e+01,  5.2449e-01, -1.0387e+01,  1.6340e+01, -3.0493e+00,
          4.7932e+00,  1.2574e+01,  2.9615e-01,  1.0291e+00,  3.1357e+00],
        [-1.8263e+00,  3.3516e-01,  9.5188e+00, -1.0453e+00, -8.9037e+00,
          4.9132e+00,  8.0763e+00,  8.3692e-01,  7.5167e-01, -4.9579e-01],
        [-1.0156e+01,  9.6769e-02,  5.0606e+00,  1.6720e+01, -7.0949e+00,
          6.5002e+00,  5.6688e+00,  2.2556e+00,  4.7815e-01, -5.0307e+00],
        [ 3.8829e+00, -4.2687e-02,  5.3370e-01,  1.1993e+01,  1.5190e+00,
         -6.7836e+00, -1.0248e-01, -8.7496e+00,  7.1642e-01,  9.2134e-01]])

In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
b_tensor.mm(b_tensor.reshape(10, 6))

tensor([[-3.4008, -2.0629, -3.1490, -0.5380,  5.6768, -2.6804],
        [14.4661, -1.4763,  3.2147, -3.1295, -8.0089,  0.4277],
        [ 5.8623, -2.4492,  5.3770, -2.5184, -7.5760,  0.6467],
        [-2.5985, -0.6845, -2.1552,  1.2272, -1.8714, -1.0742],
        [-1.5413,  3.6612,  1.9801,  6.8366, -5.3439,  3.9841],
        [-1.1450, -4.9538,  4.8397, -2.8257, -0.7048,  0.3429]])

In [9]:
# Создайте единичный тензор размера 5x6
x = torch.ones((5,6))

In [10]:
# Переведите его в формат numpy
x.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [11]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5

from torch.autograd import Variable


def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

# Посчитайте 

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 120
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%10:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 11, x = 1.69, y = 4.12
Iteration 21, x = 1.55, y = 3.92
Iteration 31, x = 1.47, y = 3.85
Iteration 41, x = 1.42, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 101, x = 1.34, y = 3.81
Iteration 111, x = 1.34, y = 3.81
